version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    build: .
    container_name: FacebookLiteCode
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
